language: python
sudo: false
python:
  - pypy-5.4.1
  - 3.6
  - 2.7
  - 3.5
  - 3.4

install:
  - pip install -U pip setuptools zc.buildout
  - buildout

script: bin/test

cache:
  directories:
    - $HOME/.cache/pip
    - eggs
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
